# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: files.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='files.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0b\x66iles.proto\"4\n\x0cQueryFileReq\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_hash\x18\x02 \x01(\t\"H\n\rQueryFileResp\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_hash\x18\x02 \x01(\t\x12\x11\n\tfile_size\x18\x03 \x01(\x03\x32\x35\n\x05\x46iles\x12,\n\tQueryFile\x12\r.QueryFileReq\x1a\x0e.QueryFileResp\"\x00\x62\x06proto3'
)




_QUERYFILEREQ = _descriptor.Descriptor(
  name='QueryFileReq',
  full_name='QueryFileReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='QueryFileReq.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_hash', full_name='QueryFileReq.file_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=67,
)


_QUERYFILERESP = _descriptor.Descriptor(
  name='QueryFileResp',
  full_name='QueryFileResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='QueryFileResp.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_hash', full_name='QueryFileResp.file_hash', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='file_size', full_name='QueryFileResp.file_size', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=141,
)

DESCRIPTOR.message_types_by_name['QueryFileReq'] = _QUERYFILEREQ
DESCRIPTOR.message_types_by_name['QueryFileResp'] = _QUERYFILERESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

QueryFileReq = _reflection.GeneratedProtocolMessageType('QueryFileReq', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFILEREQ,
  '__module__' : 'files_pb2'
  # @@protoc_insertion_point(class_scope:QueryFileReq)
  })
_sym_db.RegisterMessage(QueryFileReq)

QueryFileResp = _reflection.GeneratedProtocolMessageType('QueryFileResp', (_message.Message,), {
  'DESCRIPTOR' : _QUERYFILERESP,
  '__module__' : 'files_pb2'
  # @@protoc_insertion_point(class_scope:QueryFileResp)
  })
_sym_db.RegisterMessage(QueryFileResp)



_FILES = _descriptor.ServiceDescriptor(
  name='Files',
  full_name='Files',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=143,
  serialized_end=196,
  methods=[
  _descriptor.MethodDescriptor(
    name='QueryFile',
    full_name='Files.QueryFile',
    index=0,
    containing_service=None,
    input_type=_QUERYFILEREQ,
    output_type=_QUERYFILERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILES)

DESCRIPTOR.services_by_name['Files'] = _FILES

# @@protoc_insertion_point(module_scope)
