# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import api.files_pb2 as files__pb2


class FilesStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryFile = channel.unary_unary(
            '/Files/QueryFile',
            request_serializer=files__pb2.QueryFileReq.SerializeToString,
            response_deserializer=files__pb2.QueryFileResp.FromString,
        )


class FilesServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FilesServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'QueryFile': grpc.unary_unary_rpc_method_handler(
            servicer.QueryFile,
            request_deserializer=files__pb2.QueryFileReq.FromString,
            response_serializer=files__pb2.QueryFileResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Files', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))

 # This class is part of an EXPERIMENTAL API.


class Files(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryFile(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Files/QueryFile',
                                             files__pb2.QueryFileReq.SerializeToString,
                                             files__pb2.QueryFileResp.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
